
//ARBITRAGE
export const SET_ARBITRAGE_TABLE = "SET_ARBITRAGE_TABLE";
export const SET_ARBITRAGE_FAILURE = "SET_ARBITRAGE_FAILURE";

export const SET_ARBITRAGE_GRAPH_FAILURE = "SET_ARBITRAGE_GRAPH_FAILURE";
export const SET_ARBITRAGE_GRAPH = "SET_ARBITRAGE_GRAPH";
export const SET_ARBITRAGE_GRAPH_REQUEST = "SET_ARBITRAGE_GRAPH_REQUEST";

export const SET_ARBITRAGE_SMB_GRAPH_REQUEST = "SET_ARBITRAGE_SMB_GRAPH_REQUEST";
export const SET_ARBITRAGE_SMB_GRAPH = "SET_ARBITRAGE_SMB_GRAPH";
export const SET_ARBITRAGE_SMB_GRAPH_FAILURE = "SET_ARBITRAGE_SMB_GRAPH_FAILURE";

//AUTH, USER, REFERRAL => src/actions/auth/authActionTypes

//ARTICLES
export const SET_ARTICLES = "SET_ARTICLES";
export const SET_ARTICLES_FAILURE = "SET_ARTICLES_FAILURE";

//FAQ
export const SET_FAQ = "SET_FAQ";
export const SET_FAQ_FAILURE = "SET_FAQ_FAILURE";
export const SET_FAQ_REQUEST = "SET_FAQ_REQUEST";


//INVEST
export const SET_INVESTS = "SET_INVESTS";
export const SET_INVESTS_FAILURE = "SET_INVESTS_FAILURE";
export const SET_INVESTS_REQUEST = "SET_INVESTS_REQUEST";
export const SEND_INVEST_REQUEST = "SEND_INVEST_REQUEST";
export const SEND_INVEST_SUCCESS = "SEND_INVEST_SUCCESS";
export const SEND_INVEST_FAILURE = "SEND_INVEST_FAILURE";
export const UPLOAD_INVEST_FILE_REQUEST = "UPLOAD_INVEST_FILE_REQUEST";
export const UPLOAD_INVEST_FILE_FAILURE = "UPLOAD_INVEST_FILE_FAILURE";
export const UPLOAD_INVEST_FILE_SUCCESS = "UPLOAD_INVEST_FILE_SUCCESS";
export const CHANGE_INVEST_STEP = "CHANGE_INVEST_STEP";
export const SET_ACTIVE_INVEST = "SET_ACTIVE_INVEST";

export const GET_TOKEN_INVESTS_REQUEST = "GET_TOKEN_INVESTS_REQUEST";
export const GET_TOKEN_INVESTS_FAILURE = "GET_TOKEN_INVESTS_FAILURE";
export const GET_TOKEN_INVESTS_SUCCESS = "GET_TOKEN_INVESTS_SUCCESS";


//KYC
export const SEND_KYC_REQUEST = "SEND_KYC_REQUEST";
export const SEND_KYC_FAILURE = "SEND_KYC_FAILURE";
export const SEND_KYC_SUCCESS = "SEND_KYC_SUCCESS";
export const FETCH_KYC_STATUS = "FETCH_KYC_STATUS";


//LEVELS
export const SET_LEVELS = "SET_LEVELS";
export const SET_LEVELS_REQUEST = "SET_LEVELS_REQUEST";
export const SET_LEVELS_FAILURE = "SET_LEVELS_FAILURE";


//PROFIT
export const SET_PROFIT_HISTORY = " SET_PROFIT_HISTORY";
export const SET_PROFIT_HISTORY_FAILURE = " SET_PROFIT_HISTORY_FAILURE";
export const SET_PROFIT_HISTORY_REQUEST = " SET_PROFIT_HISTORY_REQUEST";
export const SET_PROFIT_CHART_REQUEST = " SET_PROFIT_CHART_REQUEST";
export const SET_PROFIT_CHART_HISTORY = " SET_PROFIT_CHART_HISTORY";
export const SET_PROFIT_CHART_HISTORY_FAILURE = " SET_PROFIT_CHART_HISTORY_FAILURE";


//TRANSACTION
export const SET_TRANSACTION_HISTORY = " SET_TRANSACTION_HISTORY";
export const SET_TRANSACTION_HISTORY_FAILURE = " SET_TRANSACTION_HISTORY_FAILURE";
export const SET_TRANSACTION_HISTORY_REQUEST = " SET_TRANSACTION_HISTORY_REQUEST";

export const GET_TOKEN_TRANSACTION_HISTORY_REQUEST = " GET_TOKEN_TRANSACTION_HISTORY_REQUEST";
export const GET_TOKEN_TRANSACTION_HISTORY_SUCCESS = " GET_TOKEN_TRANSACTION_HISTORY_SUCCESS";
export const GET_TOKEN_TRANSACTION_HISTORY_FAILURE = " GET_TOKEN_TRANSACTION_HISTORY_FAILURE";


//WITHDRAWAL
export const SET_WITHDRAWALS = "SET_WITHDRAWALS";
export const SET_WITHDRAWALS_FAILURE = "SET_WITHDRAWALS_FAILURE";
export const SET_WITHDRAWALS_REQUEST = "SET_WITHDRAWALS_REQUEST";
export const SEND_WITHDRAWAL_REQUEST = "SEND_WITHDRAWAL_REQUEST";
export const SEND_WITHDRAWAL_SUCCESS = "SEND_WITHDRAWAL_SUCCESS";
export const SEND_WITHDRAWAL_FAILURE = "SEND_WITHDRAWAL_FAILURE";


//COUNTRIES
export const SET_COUNTRIES = "SET_COUNTRIES";
export const SET_COUNTRIES_CODES = "SET_COUNTRIES_CODES";

//START REPORT
export const GET_USER_FULL_DETAILS_REQUEST = "GET_USER_FULL_DETAILS_REQUEST";
export const GET_USER_FULL_DETAILS_SUCCESS = "GET_USER_FULL_DETAILS_SUCCESS";
export const GET_USER_FULL_DETAILS_FAILURE = "GET_USER_FULL_DETAILS_FAILURE";

export const GET_USER_TOKEN_FULL_DETAILS_REQUEST = "GET_USER_TOKEN_FULL_DETAILS_REQUEST";
export const GET_USER_TOKEN_FULL_DETAILS_SUCCESS = "GET_USER_TOKEN_FULL_DETAILS_SUCCESS";
export const GET_USER_TOKEN_FULL_DETAILS_FAILURE = "GET_USER_TOKEN_FULL_DETAILS_FAILURE";

export const GET_USER_TOKEN_SMB_PRICE_CHART_REQUEST = "GET_USER_TOKEN_SMB_PRICE_CHART_REQUEST";
export const GET_USER_TOKEN_SMB_PRICE_CHART_SUCCESS = "GET_USER_TOKEN_SMB_PRICE_CHART_SUCCESS";
export const GET_USER_TOKEN_SMB_PRICE_CHART_FAILURE = "GET_USER_TOKEN_SMB_PRICE_CHART_FAILURE";

export const GET_MARKET_DETAIL_REQUEST = "GET_MARKET_DETAIL_REQUEST";
export const GET_MARKET_DETAIL_SUCCESS = "GET_MARKET_DETAIL_SUCCESS";
export const GET_MARKET_DETAIL_FAILURE = "GET_MARKET_DETAIL_FAILURE";

export const GET_RESOURCE_DETAIL_REQUEST = "GET_RESOURCE_DETAIL_REQUEST";
export const GET_RESOURCE_DETAIL_SUCCESS = "GET_RESOURCE_DETAIL_SUCCESS";
export const GET_RESOURCE_DETAIL_FAILURE = "GET_RESOURCE_DETAIL_FAILURE";

export const GET_RESOURCE_DETAIL_WITH_DATE_REQUEST = "GET_RESOURCE_DETAIL_WITH_DATE_REQUEST";
export const GET_RESOURCE_DETAIL_WITH_DATE_SUCCESS = "GET_RESOURCE_DETAIL_WITH_DATE_SUCCESS";
export const GET_RESOURCE_DETAIL_WITH_DATE_FAILURE = "GET_RESOURCE_DETAIL_WITH_DATE_FAILURE";

export const GET_PROFIT_DATA_REQUEST = "GET_PROFIT_DATA_REQUEST";
export const GET_PROFIT_DATA_SUCCESS = "GET_PROFIT_DATA_SUCCESS";
export const GET_PROFIT_DATA_FAILURE = "GET_PROFIT_DATA_FAILURE";